### ISSUE TITLE
Code  & Data release time

### ISSUE THREAD

**Issue by skyerguo** [LCS2-IIITD/ChatterNet#1]
I have read your ChatterNet paper on KDD20, it provides this link for anonymous code and data. However, it is now empty. I am wondering when can you release your code and data? Thanks!

**Comment by sara-02** [comment]
Hey @skyerguo Thanks for reaching out, the authors are caught up in a deadline, we will release the code here itself by coming weekend.

Sorry we could not follow up on this earlier.

**Comment by skyerguo** [comment]
> Hey @skyerguo Thanks for reaching out, the authors are caught up in a deadline, we will release the code here itself by coming weekend.
> 
> Sorry we could not follow up on this earlier.

Hi @sara-02 . I view the repository, it is still empty now LOL. May I have your released code here soon?
Thanks for your quick response.

**Comment by sara-02** [comment]
@skyerguo We added the code and instructions. You can review it now. 
I will be closing this issue, we can open issues specific to any code snippet.
